{{- if .Values.checkoutService.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.checkoutService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.checkoutService.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.checkoutService.name }}
    spec:
      containers:
      - name: {{ .Values.checkoutService.name }}
        image: pellepedro/skyramp-godebug:0.0.1
        workingDir: /src
        ports:
        - containerPort:  {{ .Values.checkoutService.containerPort }}
        env:
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "{{ .Values.productCatalogService.name }}:{{ .Values.productCatalogService.containerPort }}"
          - name: SHIPPING_SERVICE_ADDR
            value: "{{ .Values.shippingService.name }}:{{ .Values.shippingService.containerPort }}"
          - name: PAYMENT_SERVICE_ADDR
            value:  "{{ .Values.paymentService.name }}:{{ .Values.paymentService.containerPort }}"
          - name: EMAIL_SERVICE_ADDR
            value: "{{ .Values.emailService.name }}:{{ .Values.emailService.containerPort }}"
          - name: CURRENCY_SERVICE_ADDR
            value: "{{ .Values.currencyService.name }}:{{ .Values.currencyService.containerPort }}"
          - name: CART_SERVICE_ADDR
            value: "{{ .Values.cartService.name }}:{{ .Values.cartService.containerPort }}"
        securityContext:
          capabilities:
            add:
              - SYS_PTRACE
        volumeMounts:
          - name: checkout-service-mount
            mountPath: /src
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
      volumes:
        - name: checkout-service-mount
          hostPath:
            path: /checkoutservice
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    skyramp.dev/protocol: {{ .Values.checkoutService.protocol}}
  name: {{ .Values.checkoutService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port:  {{ .Values.checkoutService.servicePort}}
    name: {{ .Values.checkoutService.name }}
  selector:
    name: {{ .Values.checkoutService.name }}
{{- end }}
