{{- if .Values.currencyService.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.currencyService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.currencyService.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.currencyService.name }}
    spec:
      containers:
      - name: {{ .Values.currencyService.name }}
        image: {{ .Values.currencyService.image.repository }}:{{ .Values.currencyService.image.tag }}
        ports:
        - containerPort:  {{ .Values.currencyService.containerPort }}
        env:
          - name: PORT
            value: "{{ .Values.currencyService.containerPort }}"
          - name: DISABLE_TRACING
            value: "1"
          - name: DISABLE_PROFILER
            value: "1"
          - name: DISABLE_DEBUGGER
            value: "1"

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    skyramp.dev/protocol: {{ .Values.currencyService.protocol}}
  name: {{ .Values.currencyService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port:  {{ .Values.currencyService.servicePort}}
    name: {{ .Values.currencyService.name }}
  selector:
    name: {{ .Values.currencyService.name }}
{{- end }}
