{{- if .Values.shippingService.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.shippingService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.shippingService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.shippingService.name }}
    spec:
      containers:
      - name: {{ .Values.shippingService.name }}
        image: {{ .Values.shippingService.image.repository }}:{{ .Values.shippingService.image.tag }}
        ports:
        - containerPort:  {{ .Values.shippingService.containerPort }}
        env:
          - name: PORT
            value: "{{ .Values.shippingService.containerPort }}"
          - name: DISABLE_TRACING
            value: "1"
          - name: DISABLE_PROFILER
            value: "1"
          - name: DISABLE_DEBUGGER
            value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.shippingService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port:  {{ .Values.shippingService.servicePort}}
    name: {{ .Values.shippingService.name }}
    protocol: {{ .Values.shippingService.protocol}} 
  selector:
    app: {{ .Values.shippingService.name }}
{{- end }}
