version: v1
services:
  - name: cart-service
    port: 50000
    protocol: thrift
    secure: false
    thriftOptions:
      protocol: "binary"
      buffered: true
      http: true
      framed: false
endpoints:
  - name: CartService
    defined:
      name: CartService
      path: "thrift/demo.thrift"
    serviceName: cart-service
    methods:
      - name: AddItem