services:
  python_dev:
    image: python:3.10-slim
    network_mode: "host"
    volumes:
      - .:/workspace
      # SSH directory for Linux, OSX and WSL
      - ~/.ssh:/root/.ssh:z
      # Docker socket to access Docker server
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: [ "sh", "-c", "while sleep 3600; do :; done" ]
