containers:
  - name: product-catalog-service
    image:
      repository: public.ecr.aws/j1n2c2p2/microservices-demo/productcatalogservice
      tag: v0.3.9
    manifests:
      - gcp-microservices-demo/deploy/kubernetes/kubernetes-manifests.yaml
    ports:
      - product-catalog-service-port60000
    envs:
      PORT: "3550"
      DISABLE_STATS: "1"
      DISABLE_PROFILER: "1"
      DISABLE_TRACING: "1"

ports:
  - name: product-catalog-service-port60000
    port: 60000
    protocol: rest
    endpoints:
      - product-catalog-service

endpoints:
  - name: product-catalog-service
    path: "/get-product"
    methods:
      - type: 'GET'
        output: get-product-output

signatures:
  - name: get-product-output
