# This file was generated on 2023-11-01_11-16-43.
# This file contains references to generated endpoints residing in the "endpoints" folder.
# Visit https://skyramp.dev/docs/ for instructions on making changes to this scenario configuration file.
version: v1
requests:
    # `checkout-service_2ASc` endpoint is defined in file `endpoints/checkout-service-3Kdq.yaml`
    - name: PlaceOrder_QQEf
      blob: |-
        {
            "userId": "abcde",
            "userCurrency": "USD",
            "address": {
              "streetAddress": "1600 Amp street",
              "city": "Mountain View",
              "state": "CA",
              "country": "USA",
              "zipCode": 94043
            },
            "email": "someone@example.com",
            "creditCard": {
                "creditCardNumber": "4432-8015-6152-0454",
                "creditCardCvv": 672,
                "creditCardExpirationYear": 2024,
                "creditCardExpirationMonth": 1
            }
        }
      endpointName: checkout-service_2ASc
      methodName: PlaceOrder
