{{- if .Values.adService.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.adService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.adService.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.adService.name }}
    spec:
      containers:
      - name: {{ .Values.adService.name }}
        image: {{ .Values.adService.image.repository }}:{{ .Values.adService.image.tag }}
        ports:
        - containerPort:  {{ .Values.adService.containerPort }}

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    skyramp.dev/protocol: {{ .Values.adService.protocol}}
  name: {{ .Values.adService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port:  {{ .Values.adService.servicePort}}
    name: {{ .Values.adService.name }} 
  selector:
    name: {{ .Values.adService.name }}
{{- end }}
