{{- if .Values.emailService.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.emailService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.emailService.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.emailService.name }}
    spec:
      containers:
      - name: {{ .Values.emailService.name }}
        image: {{ .Values.emailService.image.repository }}:{{ .Values.emailService.image.tag }}
        ports:
        - containerPort:  {{ .Values.emailService.containerPort }}

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    skyramp.dev/protocol: {{ .Values.emailService.protocol}}
  name: {{ .Values.emailService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port:  {{ .Values.emailService.servicePort}}
    name: {{ .Values.emailService.name }}
  selector:
    name: {{ .Values.emailService.name }}
{{- end }}
