{{- if .Values.productCatalogService.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.productCatalogService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.productCatalogService.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.productCatalogService.name }}
    spec:
      containers:
      - name: {{ .Values.productCatalogService.name }}
        image: {{ .Values.productCatalogService.image.repository }}:{{ .Values.productCatalogService.image.tag }}
        ports:
        - containerPort:  {{ .Values.productCatalogService.containerPort }}
        env:
          - name: PORT
            value: "{{ .Values.productCatalogService.containerPort }}"
          - name: DISABLE_STATS
            value: "1"
          - name: DISABLE_PROFILER
            value: "1"
          - name: DISABLE_TRACING
            value: "1"

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    skyramp.dev/protocol: {{ .Values.productCatalogService.protocol}}
  name: {{ .Values.productCatalogService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port:  {{ .Values.productCatalogService.servicePort}}
    name: {{ .Values.productCatalogService.name }}
  selector:
    name: {{ .Values.productCatalogService.name }}
{{- end }}
