services:
  adservice:
    build:
      context: ./adservice/.
      dockerfile: Dockerfile
    image: public.ecr.aws/j1n2c2p2/microservices-demo/adservice:v0.3.9
  cartservice:
    build:
      context: ./cartservice/.
      dockerfile: Dockerfile
    image: public.ecr.aws/j1n2c2p2/microservices-demo/cartservice:v0.3.9
  checkoutservice:
    build:
      context: ./checkoutservice/.
      dockerfile: Dockerfile
    image: public.ecr.aws/j1n2c2p2/microservices-demo/checkoutservice:v0.3.9
  currencyservice:
    build:
      context: ./currencyservice/.
      dockerfile: Dockerfile
    image: public.ecr.aws/j1n2c2p2/microservices-demo/currencyservice:v0.3.9
  emailservice:
    build:
      context: ./emailservice/.
      dockerfile: Dockerfile
    image: public.ecr.aws/j1n2c2p2/microservices-demo/emailservice:v0.3.9
  frontend:
    build:
      context: ./frontend/.
      dockerfile: Dockerfile
    image: public.ecr.aws/j1n2c2p2/microservices-demo/frontend:v0.3.9
  paymentservice:
    build:
      context: ./paymentservice/.
      dockerfile: Dockerfile
    image: public.ecr.aws/j1n2c2p2/microservices-demo/paymentservice:v0.3.9
  productcatalogservice:
    build:
      context: ./productcatalogservice/.
      dockerfile: Dockerfile
    image: public.ecr.aws/j1n2c2p2/microservices-demo/productcatalogservice:v0.3.9
  recommendationservice:
    build:
      context: ./recommendationservice/.
      dockerfile: Dockerfile
    image: public.ecr.aws/j1n2c2p2/microservices-demo/recommendationservice:v0.3.9
  shippingservice:
    build:
      context: ./shippingservice/.
      dockerfile: Dockerfile
    image: public.ecr.aws/j1n2c2p2/microservices-demo/shippingservice:v0.3.9
  dnsmasq:
    build:
      context: ./dnsmasq/.
      dockerfile: Dockerfile
    image: public.ecr.aws/j1n2c2p2/rampup/dnsmasq:v0.4.0
