services:
  #adservice:
  #  build:
  #    context: ./adservice/.
  #    dockerfile: Dockerfile
  #  image: public.ecr.aws/j1n2c2p2/microservices-demo/adservice:coverage
  #  env_file:
  #    - 'variables.env'
  #  environment:
  #    - PORT=9550
  cartservice:
    build:
      context: ./cartservice/.
      dockerfile: Dockerfile
    image: public.ecr.aws/j1n2c2p2/microservices-demo/cartservice:coverage
    env_file:
      - 'variables.env'
    environment:
      - PORT=7070
  checkoutservice:
    build:
      context: ./checkoutservice/.
      dockerfile: Dockerfile
    image: public.ecr.aws/j1n2c2p2/microservices-demo/checkoutservice:coverage
    env_file:
      - 'variables.env'
    environment:
      - PORT=5050
  currencyservice:
    build:
      context: ./currencyservice/.
      dockerfile: Dockerfile
    image: public.ecr.aws/j1n2c2p2/microservices-demo/currencyservice:coverage
    env_file:
      - 'variables.env'
    environment:
      - PORT=7000
    ports:
      - 50000:50000
      - 60000:60000
  emailservice:
    build:
      context: ./emailservice/.
      dockerfile: Dockerfile
    image: public.ecr.aws/j1n2c2p2/microservices-demo/emailservice:coverage
    env_file:
      - 'variables.env'
    environment:
      - PORT=5000
  frontend:
    build:
      context: ./frontend/.
      dockerfile: Dockerfile
    image: public.ecr.aws/j1n2c2p2/microservices-demo/frontend:coverage
    ports:
      - 8080:80
    env_file:
      - 'variables.env'
    environment:
      - PORT=80
  paymentservice:
    build:
      context: ./paymentservice/.
      dockerfile: Dockerfile
    image: public.ecr.aws/j1n2c2p2/microservices-demo/paymentservice:coverage
    env_file:
      - 'variables.env'
    environment:
      - PORT=50051
  productcatalogservice:
    build:
      context: ./productcatalogservice/.
      dockerfile: Dockerfile
    image: public.ecr.aws/j1n2c2p2/microservices-demo/productcatalogservice:coverage
    env_file:
      - 'variables.env'
    environment:
      - PORT=3550
        # recommendationservice:
        #   build:
        #     context: ./recommendationservice/.
        #     dockerfile: Dockerfile
        #   image: public.ecr.aws/j1n2c2p2/microservices-demo/recommendationservice:coverage
        #   env_file:
        #     - 'variables.env'
        #   environment:
        #     - PORT=8080
  shippingservice:
    build:
      context: ./shippingservice/.
      dockerfile: Dockerfile
    image: public.ecr.aws/j1n2c2p2/microservices-demo/shippingservice:coverage
    env_file:
      - 'variables.env'
    environment:
      - PORT=50051
 
